Initial config for next js
platzily/platzily-monolith pull request #79
Opened 2021-11-13 23:02 UTC by jito-jito

2021-11-16 04:08 UTC, gh0stl1m submitted a review, later dismissed
LGTM

2021-11-16 17:02 UTC, omarefg requested changes

2021-11-16 17:02 UTC, omarefg commented on packages/web-client/pages/_app.js
> +function app({ Component, pageProps }) {
Lets change this to App instead please. Component names should always starts with camel case.

2021-11-17 17:03 UTC, jito-jito commented on packages/web-client/pages/_app.js
> +function app({ Component, pageProps }) {
Yes no problem, ready 👍.

2021-11-23 16:15 UTC, omarefg approved these changes, later dismissed

2021-11-30 01:31 UTC, jinfanv approved these changes

2021-11-30 01:31 UTC, jonattan-infante commented on packages/web-client/package.json
> +    "jest": "^27.3.1",
Delete jest for this packeges.json because this dependency is in the global context @jito-jito

2021-12-01 16:18 UTC, omarefg approved these changes

2021-12-01 22:33 UTC, merged